spring:
  application:
    name: jobportal

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:jobportal}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}

  jpa:
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${HIBERMATE_FORMAT_SQL:true}
        default_batch_fetch_size: ${DEFAULT_BATCH_FETCH_SIZE:50}
#    hibernate:
#      ddl-auto: none

#  cache:
#    type: CAFFEINE
#    cache-names:
#      - jobs,companies,roles
#    caffeine:
#      spec: maximumSize=5000,expireAfterWrite=1m

logging:
  pattern:
#    console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
    file: ${"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}
#  level:
#   root: ${LOG_LEVEL:INFO}
#    com.eazybytes.jobportal: ${LOG_LEVEL:INFO}
#    jobportal_error: ${LOG_LEVEL_ERROR:ERROR}
  group:
    jobportal_error: com.eazybytes.jobportal.company,com.eazybytes.jobportal.security,com.eazybytes.jobportal.contact
  file:
    name: logs/jobportal.log